<?php
?>
<?php
/**
 * @see Mage_Page_Block_Template_Links
 */
?>
<?php $_links = $this->getLinks(); ?>
<?php if (count($_links) > 0): ?>
    <li class="dropdown"><a><i class="fa fa-cog fa-2x "></i></a>
        <ul class="account"<?php if ($this->getName()): ?> id="<?php echo $this->getName() ?>"<?php endif; ?>>
            <?php foreach ($_links as $_link): ?>
                <?php if ($_link instanceof Mage_Core_Block_Abstract): ?>
                    <?php echo $_link->toHtml() ?>
                <?php else: ?>
                    <?php if ($_link->getIsLast()): ?>
                        <li><?php echo $this->getChildHtml('store_language') ?></li>
                    <?php endif; ?>
                    <li<?php if ($_link->getIsFirst() || $_link->getIsLast()): ?> class="<?php if ($_link->getIsFirst()): ?>first<?php endif; ?><?php if ($_link->getIsLast()): ?> last<?php endif; ?>"<?php endif; ?> <?php echo $_link->getLiParams() ?>><?php echo $_link->getBeforeText() ?>
                        <a href="<?php echo $_link->getUrl() ?>" title="<?php echo $_link->getTitle() ?>" <?php echo $_link->getAParams() ?>><?php echo $_link->getLabel() ?></a><?php echo $_link->getAfterText() ?>
                    </li>
                <?php endif; ?>
            <?php endforeach; ?>
        </ul>
    </li>
<?php endif; ?>
<li><a><i class="fa fa-shopping-bag fa-2x"></i></a></li>











