<?php
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->toHtml() ?></div>
<div class="page-title">
    <h1><?php echo Mage::helper('contacts')->__('Home  >  <span>Contact Us</span>') ?></h1>
</div>
<div class="wrap-contact">
<form action="<?php echo $this->getFormAction(); ?>" id="contactForm" method="post">
    <div class="fieldset">
        <h2 class="legend"><?php echo Mage::helper('contacts')->__('') ?></h2>
        <div class="map">
            <h2>You can see us on Google Map</h2>
            <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d151986.0055179955!2d-2.3635471296422184!3d53.47236790490662!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x487a4d4c5226f5db%3A0xd9be143804fe6baa!2sM%C3%A1nchester%2C+Manchester!5e0!3m2!1ses!2suk!4v1523546375816" width="100%" height="550" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <div class="icons-contact">
            <div>
                <span><i class="fa fa-phone fa-2x"></i></span>
                <p>+35 654 786 987</p>
            </div>
            <div>
                <span><i class="fa fa-map-marker fa-2x"></i></span>
                <p>Any, Rosytower Manchester - UK </p>
            </div>
            <div>
                <span><i class="fa fa-envelope-open fa-2x"></i></span>
                <p>Contact@selashop.com</p>
            </div>
        </div>
        <ul class="form-list">
            <div class="inpus-box">
            <li class="fields">
                <div class="field">
                    <div class="input-box">
                        <input name="name" placeholder="<?php echo Mage::helper('contacts')->__('NAME') ?>" id="name" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Name')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserName()) ?>" class="input-text required-entry" type="text" />
                    </div>
                </div>
                <div class="field">
                    <div class="input-box">
                        <input name="email" placeholder="<?php echo Mage::helper('contacts')->__('EMAIL') ?>" id="email" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Email')) ?>" value="<?php echo $this->escapeHtml($this->helper('contacts')->getUserEmail()) ?>" class="input-text required-entry validate-email" type="text" />
                    </div>
                </div>
            </li>
            <li>
                <div class="input-box">
                    <input name="telephone" placeholder="<?php echo Mage::helper('contacts')->__('TELEPHONE') ?>" id="telephone" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Telephone')) ?>" value="" class="input-text required" type="text" />
                </div>
            </li>
            </div>
            <li class="wide">
                <div class="input-box">
                    <textarea name="comment" placeholder="<?php echo Mage::helper('contacts')->__('COMMENT') ?>" id="comment" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Comment')) ?>" class="required-entry input-text" cols="5" rows="3"></textarea>
                </div>
            </li>
        </ul>
    </div>
    <div class="buttons-set">
        <p class="required"><?php echo Mage::helper('contacts')->__('* Required Fields') ?></p>
        <input type="text" name="hideit" id="hideit" value="" style="display:none !important;" />
        <button type="submit" title="<?php echo Mage::helper('core')->quoteEscape(Mage::helper('contacts')->__('Submit')) ?>" class="button"><span><span><?php echo Mage::helper('contacts')->__('SEND MESSAGE') ?></span></span></button>
    </div>
</form>
</div>
<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactForm', true);
//]]>
</script>
