<div class="footer-container" xmlns="http://www.w3.org/1999/html">
    <div class="footer">
        <div class="wrap-footer">
        <?php echo $this->getChildHtml() ?>
        <div class="footer-logo">
            <h1 class="logo-small">
            <a href="#"><img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>"></a>
            </h1>
            <p>Rosi - Multi Purpose<br>eCommerce PSD Template</p>
            <div class="social">
                <a><i class="fa fa-facebook-f"></i></a>
                <a><i class="fa fa-twitter"></i></a>
                <a><i class="fa fa-youtube-play"></i></a>
                <a><i class="fa fa-camera"></i></a>
            </div>
        </div>
        <div class="useful-link">
            <h6>Useful Links</h6>
            <a class="#">My Account</a>
            <a href="#">Internet-Based Ads</a>
            <a href="#">Terms of Use</a>
            <a href="#">Shipping Information</a>
            <a href="#">Gift Voucher</a>
        </div>
        <div class="customer-care">
            <h6>Customer Care</h6>
            <a href="#">Customer Care</a>
            <a href="#">Terms & Condition</a>
            <a href="#">Privacy Policy</a>
            <a href="#">Contact Us</a>
            <a href="http://local.selashop.com/sales/guest/form/" title="Orders and Returns">Return Policy</a>
        </div>
        <div class="business-hours">
            <h6>Business Hours</h6>
            <table>
                <tr>
                    <td>Mon - Fri:</td>
                    <td class="space"></td>
                    <td>8AM - 5PM</td>
                </tr>
                <tr>
                    <td>Sat:</td>
                    <td class="space"></td>
                    <td>8AM - 11PM</td>
                </tr>
                <tr>
                    <td>Sun:</td>
                    <td class="space"></td>
                    <td class="right-closed">Closed</td>
                </tr>
            </table>
            <p>We work  all the Holidays</p>
        </div>
        </div>
    </div>
<!--    <address>--><?php //echo $this->getCopyright() ?><!--</address>-->
</div>