<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_clients')->toHtml(); ?>
<div class="footer-container" xmlns="http://www.w3.org/1999/html">
    <div class="footer">
        <div class="wrap-footer">
<!--        --><?php //echo $this->getChildHtml() ?>
        <div class="footer-logo">
            <h1 class="logo-small">
            <a href="#"><img src="<?php echo $this->getLogoSrcSmall() ?>" alt="<?php echo $this->getLogoAlt() ?>"></a>
            </h1>
            <p>Rosi - Multi Purpose<br>eCommerce PSD Template</p>
            <div class="social">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_social')->toHtml(); ?>
            </div>
        </div>
        <div class="useful-link">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_useful')->toHtml(); ?>
        </div>
        <div class="customer-care">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_links_customer_care')->toHtml(); ?>
        </div>
        <div class="business-hours">
            <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('footer_business_hours')->toHtml(); ?>
        </div>
        </div>
    </div>
<!--    <address>--><?php //echo $this->getCopyright() ?><!--</address>-->
</div>
