<?php
?>
<div class="wrap-header">
<div class="header-container">
    <div class="header">
        <?php if ($this->getIsHomePage()):?>
        <h1 class="logo">
            <strong><?php echo $this->getLogoAlt() ?></strong>
            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
                <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
            </a>
        </h1>
        <?php else:?>
        <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLogoAlt() ?>" class="logo">
            <strong><?php echo $this->getLogoAlt() ?></strong>
            <img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" />
        </a>
        <?php endif?>
    </div>
</div>
<?php echo $this->getChildHtml('topMenu') ?>
    <div class="quick-access">
        <ul>
            <li>
                <?php echo $this->getChildHtml('topSearch') ?>
            </li>
<!--       <a><i class="fa fa-user"></i></a>-->
<!--        <a><i class="fa fa-shopping-bag"></i></a>-->

<!--<p class="welcome-msg">-->
<!--    --><?php //echo $this->getChildHtml('welcome') ?>
<!---->
<!--    --><?php //echo $this->getAdditionalHtml() ?>
<!--</p>-->
        <?php echo $this->getChildHtml('topLinks') ?>
        </ul>
<!--        --><?php //echo $this->getChildHtml('store_language') ?>
    </div>
<?php echo $this->getChildHtml('topContainer'); ?>
</div>
